services:
  backend:
    build:
      context: ./cmd/
      dockerfile: ./Dockerfile
    ports:
      - 8081:8080
  frontend:
    volumes:
      - ./frontend:/frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 5173:5173
